workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Generate android folder only if missing
        script: |
          if [ ! -d "android" ]; then
            flutter create . --platforms=android
          fi
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build APK (release)
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
